[workspace]
authors = ["Edwin Hu <eddyhu@gmail.com>"]
channels = ["conda-forge"]
name = "sec-sro-rss"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.2,<3.15"
requests = ">=2.32.5,<3"
beautifulsoup4 = ">=4.14.3,<5"
lxml = ">=6.0.2,<7"
feedgen = ">=1.0.0,<2"
